### PR TITLE
Translate to spanish

### PR DESCRIPTION
**Pull request by edulchan**

### CODE REVIEW

**Comment by edulchan** [comment]
Translate to spanish

**Comment by 777arc** [comment]
Awesome effort!  Are you using google translate or chatgpt or deepL, then manually tweaking?  If so which one, out of curiosity.

**Comment by 777arc** [comment]
oh also the DOA and Phaser chapters are a work in progress so you're best off not including those yet

**Comment by edulchan** [comment]
At the moment I am using Google Translate and then I correct manually, by the way, would you recommend me for previewing the rst files. On github it does not show the equations, or anything that has to do with latex code.

**Comment by 777arc** [comment]
Depends, are you on windows Linux or Mac? If windows, do you have wsl already set up?

**Comment by edulchan** [comment]
I work on windows, and at the moment I do not have wsl installed

**Comment by 777arc** [comment]
OK for now see if "RST Preview" extension in VSCode works for you, but I'll try to add instructions for building the textbook on Windows to the README because there was another guy who wants it too

**Comment by edulchan** [comment]
Thanks a lot.

**Comment by 777arc** [comment]
OK the README now has Windows instructions, let me know if they don't work for you

**Comment by edulchan** [comment]
Doesn't work on Windows. I tried it on WSL, where it works better, but it still doesn't generate the index-es.html properly because it doesn't create the content bar for each chapter. However, individual pages for the site are generated correctly. What could be wrong? Maybe something in the make file.
make_html-es

**Comment by edulchan** [comment]
I made a PR to update files

**Comment by 777arc** [comment]
Later today I can get the ES working, there were several steps I had to do for each new language

**Comment by edulchan** [comment]
Ok, I'll continue with the translation in the meantime.

**Comment by 777arc** [comment]
OK I pushed a change that should fix the build, in WSL you should be able to 
`make html-es` and the output will be in something like-
file://wsl.localhost/Ubuntu-22.04/home/YOURNAME/PySDR/_build/es/index-es.html

**Comment by edulchan** [comment]
I'm update PR, but index-es.html doesn't still show de navigation bar on left side.
compile_es

**Comment by 777arc** [comment]
hmm, try deleting your _build directory and then run make html-es twice in a row.

image

**Comment by edulchan** [comment]
I deleted the _build folder, and now is working fine

**Pull request closed without merging**
